/*
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CollectionData struct {
	Ids       []string            `json:"ids,omitempty"`
	Documents []string            `json:"documents,omitempty"`
	Metadatas []map[string]string `json:"metadatas,omitempty"`
}
