/*
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type QueryEmbedding struct {
	Where           map[string]string `json:"where,omitempty"`
	WhereDocument   map[string]string `json:"where_document,omitempty"`
	QueryEmbeddings [][]float32       `json:"query_embeddings"`
	NResults        int32             `json:"n_results,omitempty"`
	Include         []string          `json:"include,omitempty"`
}
