/*
ChromaDB API

This is OpenAPI schema for ChromaDB API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// IncludeInner struct for IncludeInner
type IncludeInner struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *IncludeInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(IncludeInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *IncludeInner) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableIncludeInner struct {
	value *IncludeInner
	isSet bool
}

func (v NullableIncludeInner) Get() *IncludeInner {
	return v.value
}

func (v *NullableIncludeInner) Set(val *IncludeInner) {
	v.value = val
	v.isSet = true
}

func (v NullableIncludeInner) IsSet() bool {
	return v.isSet
}

func (v *NullableIncludeInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncludeInner(val *IncludeInner) *NullableIncludeInner {
	return &NullableIncludeInner{value: val, isSet: true}
}

func (v NullableIncludeInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncludeInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
