/*
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ValidationError struct {
	Loc   []AnyOfValidationErrorLocItems `json:"loc"`
	Msg   string                         `json:"msg"`
	Type_ string                         `json:"type"`
}
