/*
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package swagger

import (
	"encoding/json"
)

// checks if the MetadataSimple type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataSimple{}

// MetadataSimple struct for MetadataSimple
type MetadataSimple struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewMetadataSimple instantiates a new MetadataSimple object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataSimple() *MetadataSimple {
	this := MetadataSimple{}
	return &this
}

// NewMetadataSimpleWithDefaults instantiates a new MetadataSimple object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataSimpleWithDefaults() *MetadataSimple {
	this := MetadataSimple{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MetadataSimple) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataSimple) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MetadataSimple) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MetadataSimple) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MetadataSimple) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataSimple) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MetadataSimple) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *MetadataSimple) SetValue(v string) {
	o.Value = &v
}

func (o MetadataSimple) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataSimple) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableMetadataSimple struct {
	value *MetadataSimple
	isSet bool
}

func (v NullableMetadataSimple) Get() *MetadataSimple {
	return v.value
}

func (v *NullableMetadataSimple) Set(val *MetadataSimple) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataSimple) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataSimple) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataSimple(val *MetadataSimple) *NullableMetadataSimple {
	return &NullableMetadataSimple{value: val, isSet: true}
}

func (v NullableMetadataSimple) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataSimple) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
