/*
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Collection struct {
	Id       string             `json:"id,omitempty"`
	Name     string             `json:"name,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
}
