/*
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetEmbedding struct {
	Ids           []string                        `json:"ids,omitempty"`
	Where         map[string]string               `json:"where,omitempty"`
	WhereDocument map[string]string               `json:"where_document,omitempty"`
	Sort          string                          `json:"sort,omitempty"`
	Limit         int32                           `json:"limit,omitempty"`
	Offset        int32                           `json:"offset,omitempty"`
	Include       []AnyOfGetEmbeddingIncludeItems `json:"include,omitempty"`
}
