/*
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeleteEmbedding struct {
	Ids           []string     `json:"ids,omitempty"`
	Where         *interface{} `json:"where,omitempty"`
	WhereDocument *interface{} `json:"where_document,omitempty"`
}
