/*
ChromaDB API

This is OpenAPI schema for ChromaDB API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EmbeddingsInner struct for EmbeddingsInner
type EmbeddingsInner struct {
	[]float32 *[]float32
	[]int32 *[]int32
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *EmbeddingsInner) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into []float32
	err = json.Unmarshal(data, &dst.[]float32);
	if err == nil {
		json[]float32, _ := json.Marshal(dst.[]float32)
		if string(json[]float32) == "{}" { // empty struct
			dst.[]float32 = nil
		} else {
			return nil // data stored in dst.[]float32, return on the first match
		}
	} else {
		dst.[]float32 = nil
	}

	// try to unmarshal JSON data into []int32
	err = json.Unmarshal(data, &dst.[]int32);
	if err == nil {
		json[]int32, _ := json.Marshal(dst.[]int32)
		if string(json[]int32) == "{}" { // empty struct
			dst.[]int32 = nil
		} else {
			return nil // data stored in dst.[]int32, return on the first match
		}
	} else {
		dst.[]int32 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(EmbeddingsInner)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *EmbeddingsInner) MarshalJSON() ([]byte, error) {
	if src.[]float32 != nil {
		return json.Marshal(&src.[]float32)
	}

	if src.[]int32 != nil {
		return json.Marshal(&src.[]int32)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableEmbeddingsInner struct {
	value *EmbeddingsInner
	isSet bool
}

func (v NullableEmbeddingsInner) Get() *EmbeddingsInner {
	return v.value
}

func (v *NullableEmbeddingsInner) Set(val *EmbeddingsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddingsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddingsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddingsInner(val *EmbeddingsInner) *NullableEmbeddingsInner {
	return &NullableEmbeddingsInner{value: val, isSet: true}
}

func (v NullableEmbeddingsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddingsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


