/*
 * FastAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateCollection struct {
	Name        string            `json:"name"`
	Metadata    map[string]string `json:"metadata,omitempty"`
	GetOrCreate bool              `json:"get_or_create,omitempty"`
}
